# Generated by Django 3.2 on 2021-05-21 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210521_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='skin',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='skin',
            name='profile',
        ),
        migrations.CreateModel(
            name='SkinOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skins', to=settings.AUTH_USER_MODEL, verbose_name='Profile')),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='profiles.skin', verbose_name='Skin')),
            ],
            options={
                'unique_together': {('profile', 'skin')},
            },
        ),
    ]
