# Generated by Django 3.2 on 2021-05-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210521_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skinownership',
            options={'ordering': ['skin__name']},
        ),
        migrations.AddField(
            model_name='skin',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
