# Generated by Django 3.2 on 2021-05-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210521_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skinownership',
            options={'ordering': ['-skin__name']},
        ),
    ]
