# Generated by Django 3.2 on 2021-05-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210521_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skinownership',
            options={},
        ),
    ]
