# Generated by Django 3.2 on 2021-06-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210521_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
